window.SUBWEB_PERSONAL_PRESET = {
  endpoint: "http://192.168.100.1:25500/sub",
  target: "clash",
  sourceUrl: "",
  configUrl: "https://raw.githubusercontent.com/vanness30214/clash-rule/main/config/metafenliu.ini",
  params: {
    include: "",
    exclude: "",
    emoji: "false",
    list: "false",
    sort: "true",
    udp: "true",
    scv: "true",
    append_type: "true",
    fdn: "true",
    expand: "false",
    classic: "true",
    tfo: "false",
    add_emoji: "false",
    remove_emoji: "false",
    append_info: "false",
    tls13: "false",
    new_name: "false",
    insert: "false",
    prepend: "false",
    script: "false",
    filename: "",
    interval: ""
  }
};
